drop table pavillon cascade;
drop table type_navire cascade;
drop table navire cascade;
drop table quai cascade;
drop table escale cascade;
drop table prestation cascade;
drop table prestation_escale cascade;
drop table tarif cascade;
drop table coeff_tarif cascade;

drop sequence pavillon_id_seq cascade;
drop sequence type_navire_id_seq cascade;
drop sequence navire_id_seq cascade;
drop sequence quai_id_seq cascade;
drop sequence escale_id_seq cascade;
drop sequence prestation_id_seq cascade;
drop sequence prestation_escale_id_seq cascade;
drop sequence tarif_id_seq cascade;
drop sequence coeff_tarif_id_seq cascade;